### PR TITLE
Pom doesn't get deployed using Maven Install plugin 3+

### LINKED ISSUE #38: artifactory maven plugin not deploying poms for OSGi bundles (packageType=bundle)
**Describe the bug**
deployment of OSGi bundles  (<package>=bundle in the pom.xml) results in the deployment only pushing the .jars, but it seems to ignore the .pom and does not push it to artifactory.

**To Reproduce**
Create an osgi-based project that uses the maven-bundle-plugin to build an OSGi bundle.  See https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html for example.  This results in a standard .jar, .-test.jar, *.pom, etc. being installed into the local mvn repository during 'install' processing.  However during 'deploy' via the artifactory maven plugin, only the .jar assets are deployed.    In contrast, the maven-deploy-plugin, if used as an alternative to the artifactory plugin will deploy the .pom as well as the jars.

**Expected behavior**
The .pom file should be pushed 

**Screenshots**
N/A

**Versions**
- Artifactory Maven plugin version: 3.4.0 and 3.2.3 (tried both)
- Artifactory version: Artifactory Professional 5.2.0 rev 50024
- Maven version: 3.3.9

**Additional context**

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://github.com/jfrog/artifactory-maven-plugin#testing-the-plugin) passed. If this feature is not already covered by the tests, I added new tests.

Fix #38 
Same fix as https://github.com/jfrog/build-info/pull/670

### CODE REVIEW

File: src/test/java/org/jfrog/buildinfo/integration/ArtifactoryPluginITest.java [hunk 1]
```diff
@@ -66,11 +66,19 @@ public class ArtifactoryPluginITest extends TestCase {
             "/artifactory/libs-snapshot-local/org/example/maven-archetype-simple/1.0-SNAPSHOT/maven-archetype-simple-1.0-SNAPSHOT.pom"
     };
 
+    public void testMultiModuleInstallPluginVer2() throws Exception {
```
Comment (eyalbe4) [inline src/test/java/org/jfrog/buildinfo/integration/ArtifactoryPluginITest.java:69]: Let's add a description for this test method, as well as the below `testMultiModuleInstallPluginVer3` method, specifically describing the difference between the two methods.

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
